"use client";
import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, Bookmark, Check, ChevronRight, Circle, Download, ExternalLink, FileText, FlaskConical, Github, Layers, ListFilter, Menu, Network, Radar, Route, Search, Settings2, Upload, X } from "lucide-react";
import { type Note, type Source, type Stage, stageMeta, REPO } from "@/lib/types";
import { useProgress } from "@/lib/progress";
import { AgentLoop } from "./agent-loop";

type View = "notes" | "paths" | "sources" | "radar" | "saved";
const views = [
  { id: "notes", label: "知识地图", icon: Network }, { id: "paths", label: "学习路线", icon: Route },
  { id: "sources", label: "来源文献", icon: BookOpen }, { id: "radar", label: "研究雷达", icon: Radar }, { id: "saved", label: "我的收藏", icon: Bookmark },
] as const;
const paths = [
  { title: "建立决策心智模型", label: "01 / STARTER", time: "2 周 · 每周 4–6 小时", description: "从概念边界到第一个 PPO 实验。", ids: ["orientation", "prerequisites", "mdp", "value-learning", "policy-gradient", "ppo", "agent-loop", "lab-rl"] },
  { title: "构建可训练的 Agent", label: "02 / BUILDER", time: "4 周 · 基础路线之后", description: "连接环境、奖励、学习器与独立评测。", ids: ["environments", "rewards", "lab-agent", "preferences", "grpo", "multi-turn-rl", "training-systems", "evaluation", "safety", "lab-agent-rl"] },
  { title: "从论文走向复现", label: "03 / RESEARCHER", time: "持续研究 · 每次一个问题", description: "带着假设阅读，保留实验的适用边界。", ids: ["multi-agent", "frontier-radar", "maintenance"] },
];

export function Atlas({ notes, sources }: { notes: Note[]; sources: Source[] }) {
  const [view, setView] = useState<View>("notes");
  const [stage, setStage] = useState<Stage | "ALL">("ALL");
  const [track, setTrack] = useState("全部主题");
  const [query, setQuery] = useState("");
  const [kind, setKind] = useState("全部类型");
  const [onlyUnread, setOnlyUnread] = useState(false);
  const [mobile, setMobile] = useState(false);
  const [message, setMessage] = useState("");
  const importInput = useRef<HTMLInputElement>(null);
  const progress = useProgress();
  const readCount = notes.filter((n) => progress.read.includes(n.id)).length;
  const tracks = [...new Set(notes.map((n) => n.track))];
  const nextNote = notes.find((n) => !progress.read.includes(n.id)) ?? notes[0];
  const latest = notes.reduce((value, note) => note.updated > value ? note.updated : value, "");
  const filtered = useMemo(() => notes.filter((note) =>
    (stage === "ALL" || stage === note.stage) && (track === "全部主题" || note.track === track) &&
    (!onlyUnread || !progress.read.includes(note.id)) && (view !== "saved" || progress.bookmarks.includes(note.id)) &&
    `${note.title} ${note.summary} ${note.tags.join(" ")} ${note.content}`.toLowerCase().includes(query.toLowerCase())
  ), [notes, stage, track, query, view, progress.read, progress.bookmarks, onlyUnread]);
  const filteredSources = sources.filter((source) => (kind === "全部类型" || source.kind === kind) && `${source.title} ${source.author} ${source.note} ${source.evidence}`.toLowerCase().includes(query.toLowerCase()));
  function navigate(target: View) { setView(target); setMobile(false); setQuery(""); setStage("ALL"); setTrack("全部主题"); setOnlyUnread(false); }
  function resetFilters() { setStage("ALL"); setTrack("全部主题"); setQuery(""); setOnlyUnread(false); }

  return <div className="workspace">
    <aside className={`sidebar ${mobile ? "mobile-open" : ""}`}>
      <Link href="/" className="brand"><span className="brand-mark"><Network size={19} /></span><span>AGENTIC RL<span className="brand-sub">ATLAS / PERSONAL KNOWLEDGE</span></span></Link>
      <button className="icon-button mobile-close" aria-label="关闭菜单" onClick={() => setMobile(false)}><X size={18} /></button>
      <p className="nav-label">WORKSPACE</p>
      <nav aria-label="主导航">{views.map(({ id, label, icon: Icon }) => <button key={id} className={`nav-item ${view === id ? "active" : ""}`} onClick={() => navigate(id)} aria-current={view === id ? "page" : undefined}><Icon size={17} /><span>{label}</span>{id === "notes" && <small>{notes.length}</small>}{id === "saved" && <small>{notes.filter((n) => progress.bookmarks.includes(n.id)).length}</small>}{id === "radar" && <span className="new-dot" />}</button>)}</nav>
      <div className="sidebar-divider" /><p className="nav-label">COLLECTIONS</p>
      <div className="collection-list">{tracks.map((item, i) => <button key={item} onClick={() => { navigate("notes"); setTrack(item); }} className={track === item ? "current" : ""}><i className={`collection-dot color-${i}`} /><span>{item}</span><small>{notes.filter((n) => n.track === item).length}</small></button>)}</div>
      <div className="sidebar-bottom"><Link href="/notes/maintenance"><Settings2 size={16} />维护协议<ArrowUpRight size={13} /></Link><a href={REPO} target="_blank" rel="noreferrer"><Github size={16} />Git 仓库<ArrowUpRight size={13} /></a><div className="sidebar-version"><span className="status-dot" />v1.0 · {latest}</div></div>
    </aside>
    {mobile && <button className="nav-backdrop" aria-label="关闭导航遮罩" onClick={() => setMobile(false)} />}
    <div className="main-pane">
      <header className="workspace-bar"><div className="breadcrumbs"><button className="icon-button mobile-menu" onClick={() => setMobile(true)} aria-label="打开菜单"><Menu size={18} /></button><span>个人知识库</span><ChevronRight size={13} /><strong>{views.find((item) => item.id === view)?.label}</strong></div><div className="bar-actions"><span className="local-label">本机阅读进度</span><button className="icon-button" title="导出阅读进度" aria-label="导出阅读进度" onClick={progress.exportData}><Download size={16} /></button><button className="icon-button" title="导入并合并阅读进度" aria-label="导入阅读进度" onClick={() => importInput.current?.click()}><Upload size={16} /></button><input hidden ref={importInput} type="file" accept="application/json,.json" onChange={async (e) => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 1000000) throw new Error("进度文件超过 1 MB。"); progress.importData(await file.text(), notes.map((n) => n.id)); setMessage("阅读进度已合并。"); } catch (error) { setMessage(error instanceof Error ? error.message : "导入失败。"); } e.target.value = ""; }} /></div></header>
      <main id="main-content" className="workspace-content">
        {(message || progress.error) && <div className="notice" role="status">{progress.error || message}<button className="icon-button" aria-label="关闭通知" onClick={() => setMessage("")}><X size={14} /></button></div>}
        <div className="page-heading"><div><p className="eyebrow"><span className="status-dot" /> RESEARCH IN PROGRESS</p><h1>Agentic RL <span>Atlas</span></h1><p className="page-subtitle">从强化学习基础，到与环境交互、持续学习的智能体。</p></div><Link className="command primary" href={`/notes/${nextNote.id}`}>{readCount === 0 ? "从这里开始" : readCount === notes.length ? "重新阅读" : "继续阅读"}<ArrowRight size={16} /></Link></div>
        <div className="metrics"><div><span>知识节点</span><strong>{String(notes.length).padStart(2, "0")}<small>篇正文</small></strong></div><div><span>精选来源</span><strong>{String(sources.length).padStart(2, "0")}<small>原始文献与博客</small></strong></div><div><span>学习路径</span><strong>03<small>入门 / 工程 / 研究</small></strong></div><div><span>阅读进度</span><strong>{Math.round(readCount / notes.length * 100)}<small>% · {readCount}/{notes.length}</small></strong><div className="progress-line"><i style={{ width: `${readCount / notes.length * 100}%` }} /></div></div></div>
        {(view === "notes" || view === "saved") && <div className="knowledge-layout"><section className="knowledge-main" aria-label="知识笔记"><div className="section-title"><h2>{view === "saved" ? "我的收藏" : "知识地图"}</h2><span className="mono muted">{filtered.length} NOTES</span></div><div className="stage-tabs" role="group" aria-label="学习阶段"><button onClick={() => setStage("ALL")} className={stage === "ALL" ? "active" : ""} aria-pressed={stage === "ALL"}>全部<span>{notes.length}</span></button>{(Object.keys(stageMeta) as Stage[]).map((item) => <button key={item} className={stage === item ? "active" : ""} aria-pressed={stage === item} onClick={() => setStage(item)}>{stageMeta[item].index} {stageMeta[item].label}<span>{notes.filter((n) => n.stage === item).length}</span></button>)}</div><div className="filter-row"><label className="search"><Search size={16} /><input aria-label="搜索知识库" placeholder="搜索概念、标签或正文…" value={query} onChange={(e) => setQuery(e.target.value)} />{query && <button className="icon-button" onClick={() => setQuery("")} aria-label="清空搜索"><X size={14} /></button>}</label><label className="filter-select"><ListFilter size={14} /><select aria-label="选择主题" value={track} onChange={(e) => setTrack(e.target.value)}><option>全部主题</option>{tracks.map((item) => <option key={item}>{item}</option>)}</select></label></div><label className="unread"><input type="checkbox" checked={onlyUnread} onChange={(e) => setOnlyUnread(e.target.checked)} />仅看未读</label>
          <div className="note-list">{filtered.map((note) => <article className="note-row" key={note.id}><button className={`read-toggle ${progress.read.includes(note.id) ? "is-read" : ""}`} aria-label={`${progress.read.includes(note.id) ? "标记未读" : "标记已读"}：${note.title}`} title={progress.read.includes(note.id) ? "标记未读" : "标记已读"} aria-pressed={progress.read.includes(note.id)} onClick={() => progress.toggle(note.id, "read")}>{progress.read.includes(note.id) ? <Check size={15} /> : <Circle size={15} />}</button><Link className="note-link" href={`/notes/${note.id}`}><div className="note-meta"><span className={`stage-label ${stageMeta[note.stage].color}`}>{stageMeta[note.stage].index} / {stageMeta[note.stage].label}</span><span>{note.track}</span><span>{note.minutes} MIN</span></div><h3>{note.title}</h3><p>{note.summary}</p><div className="tag-list">{note.tags.slice(0, 3).map((tag) => <span key={tag}>#{tag}</span>)}<span className="source-number"><FileText size={11} />{note.sources.length} 来源</span></div></Link><button className={`icon-button save-note ${progress.bookmarks.includes(note.id) ? "saved" : ""}`} aria-label={`${progress.bookmarks.includes(note.id) ? "取消收藏" : "收藏"}：${note.title}`} title={progress.bookmarks.includes(note.id) ? "取消收藏" : "收藏"} aria-pressed={progress.bookmarks.includes(note.id)} onClick={() => progress.toggle(note.id, "bookmarks")}><Bookmark size={16} fill={progress.bookmarks.includes(note.id) ? "currentColor" : "none"} /></button></article>)}</div>{filtered.length === 0 && <div className="empty"><Search size={24} /><h3>{view === "saved" ? "这里还没有匹配的收藏" : "没有找到匹配的笔记"}</h3><button className="command" onClick={resetFilters}>清空筛选</button></div>}</section>
          <aside className="context-rail"><div className="rail-heading"><Layers size={14} /><span>THE LEARNING LOOP</span></div><AgentLoop /><div className="rail-section"><span className="rail-kicker">FIRST PRINCIPLES</span><h3>Agent ≠ Agentic RL</h3><p>会调用工具，不代表经过强化学习。先确定策略、环境、奖励与参数更新发生在哪里。</p><Link href="/notes/orientation">厘清概念边界<ArrowUpRight size={14} /></Link></div><div className="rail-section"><div className="rail-heading"><Radar size={14} /><span>FRONTIER WATCH</span><span className="new-dot" /></div><Link className="radar-link" href="/notes/frontier-radar"><small>2026.09 · 待精读</small><strong>技能演化与跨框架泛化</strong><p>CoSkill / Multi-Harness RL / EDGE</p><span>打开研究雷达<ArrowUpRight size={13} /></span></Link></div><div className="rail-section"><FlaskConical size={18} className="amber" /><h3>从一个小实验开始</h3><p>CPU、PPO 与独立评测。先跑通闭环，再考虑模型规模。</p><Link href="/notes/lab-rl">实验 01<ArrowUpRight size={14} /></Link></div><div className="rail-foot mono">LAST REVIEW<br /><strong>{latest}</strong><br />{sources.length} sources · metadata checked</div></aside></div>}
        {view === "paths" && <section><div className="section-title"><h2>学习路线</h2><Link className="text-link" href="/notes/learning-paths">路线说明<ArrowUpRight size={14} /></Link></div><div className="path-grid">{paths.map((path, index) => <article className="path-item" key={path.title}><p className={`rail-kicker ${index === 0 ? "cyan" : index === 1 ? "amber" : "rose"}`}>{path.label}</p><h2>{path.title}</h2><p>{path.description}</p><span className="path-time">{path.time}</span><ol>{path.ids.map((id) => { const note = notes.find((n) => n.id === id)!; return <li key={id}><span>{progress.read.includes(id) ? <Check size={13} /> : <Circle size={11} />}</span><Link href={`/notes/${id}`}>{note.title}</Link></li>; })}</ol><div className="path-footer">{path.ids.filter((id) => progress.read.includes(id)).length}/{path.ids.length} 已读<Link href={`/notes/${path.ids.find((id) => !progress.read.includes(id)) ?? path.ids[0]}`}>进入路线<ArrowRight size={15} /></Link></div></article>)}</div></section>}
        {view === "sources" && <section><div className="section-title"><h2>来源文献</h2><span className="mono muted">{filteredSources.length} SOURCES</span></div><div className="source-intro">原始论文、作者课程与工程资料。链接核验不代表结论已复现；新预印本单独标记。</div><div className="filter-row"><label className="search"><Search size={16} /><input aria-label="搜索来源" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="标题、作者或研究方向…" /></label><select className="kind-select" aria-label="来源类型" value={kind} onChange={(e) => setKind(e.target.value)}><option>全部类型</option>{[...new Set(sources.map((source) => source.kind))].map((type) => <option key={type}>{type}</option>)}</select></div><div className="source-list">{filteredSources.map((source) => <article className="source-row" key={source.id}><span className="source-kind">{source.kind}</span><div><a href={source.url} target="_blank" rel="noreferrer"><h3>{source.title}<ExternalLink size={13} /></h3></a><p>{source.note}</p><div className="source-meta"><span>{source.author}</span><span>{source.year}</span><span className={source.evidence.includes("待精读") ? "rose" : "cyan"}>{source.evidence}</span></div><div className="cited-by">{notes.filter((note) => note.sources.includes(source.id)).map((note) => <Link key={note.id} href={`/notes/${note.id}`}>{note.title}<ChevronRight size={11} /></Link>)}</div></div><span className="source-check"><span className={`status-dot ${!source.accessible ? "error-dot" : ""}`} />{source.accessible ? "链接已核验" : "待核验"}<small>{source.checkedAt ?? "无记录"}</small></span></article>)}</div>{!filteredSources.length && <div className="empty">没有匹配的来源。<button className="command" onClick={() => { setQuery(""); setKind("全部类型"); }}>清空筛选</button></div>}</section>}
        {view === "radar" && <section><div className="section-title"><h2>研究雷达</h2><span className="mono rose">2026.08–09 / WATCHLIST</span></div><div className="radar-intro"><p>近期预印本：仅核验作者摘要，待全文精读与复现。</p><Link className="command" href="/notes/frontier-radar">阅读问题与边界<ArrowRight size={15} /></Link></div><div className="radar-grid">{sources.filter((source) => source.evidence.includes("新预印本")).map((source, index) => <article className="radar-item" key={source.id}><span className="mono rose">0{index + 1} / {source.id.toUpperCase()}</span><h3>{source.title}</h3><p>{source.note}</p><a href={source.url} target="_blank" rel="noreferrer">原始论文<ExternalLink size={14} /></a></article>)}</div><div className="radar-next"><h3>研究问题优先于排行榜</h3><p>可迁移性、长时程信用分配、经验内化和探索效率。每次选一个问题，固定模型、预算和执行框架，再验证论文的因果主张。</p><Link href="/notes/lab-agent-rl">设计一次可复现实验<ArrowUpRight size={15} /></Link></div></section>}
        <footer className="workspace-footer"><span>AGENTIC RL ATLAS <i>/</i> KNOWLEDGE IS VERSIONED</span><Link href="/notes/maintenance">维护协议<ArrowUpRight size={12} /></Link></footer>
      </main>
    </div>
  </div>;
}
